import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";

import AuthProvider from "@/components/AuthProvider";
import Header from "@/components/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;

  return (
    <html lang="en">
      <AuthProvider accessToken={accessToken}>
        <body>
          {accessToken && <Header userName={session?.user.email || ""} />}
          {children}
          {/* <ThemeRegistry options={{ key: "mui", prepend: true }}></ThemeRegistry> */}
        </body>
      </AuthProvider>
    </html>
  );
}
